// export const PRODUCTS_URL = `https://soyhenry-store.herokuapp.com/products?`;
export const URL_BASE = 'http://localhost:3001/';
const workspace = "http://localhost:3001"
export const PRODUCTS_URL = `http://localhost:3001/products?`;
export const REGISTER_URL="http://localhost:3001/auth/register";
export const LOGIN_URL="http://localhost:3001/auth/login";
export const GET_NACIONALITIES="http://localhost:3001/userflow/nacionalities";
export const GET_DOCUMENT_TYPES="http://localhost:3001/userflow/documenttypes";
export const GET_ALL_USERS= `${workspace}/admin/users`
export const CHANGE_ROL= `${workspace}/userflow/users/rol`
export const GET_ROLES= `${workspace}/userflow/role`
