// export const PRODUCTS_URL = `https://soyhenry-store.herokuapp.com/products?`;
const workspace = `http://localhost:3001`
export const PRODUCTS_URL = `${workspace}/product?`;
export const REGISTER_URL=`${workspace}/auth/register`;
export const LOGIN_URL=`${workspace}/auth/login`;
export const GET_NACIONALITIES=`${workspace}/userflow/nacionalities`;
export const GET_DOCUMENT_TYPES=`${workspace}/userflow/documenttypes`;
export const GET_ALL_USERS= `${workspace}/admin/users`
export const CHANGE_ROL= `${workspace}/userflow/users/rol`
export const CHANGE_STATUS= `${workspace}/userflow/users/status`
export const BAN_USER= `${workspace}/admin/banuser`
export const GET_ROLES= `${workspace}/userflow/role`
export const PUT_DATA_USER= `${workspace}/auth/login`
export const GET_STATUS= `${workspace}/userflow/userstatus`
